#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V
bspc config border_width         0
bspc config window_gap           8

bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color     "#6999e6"
bspc config normal_border_color      "#202A25"

#AutoStart
sxhkd &
feh --bg-scale /home/pugach/Pictures/wallpapers.png&
dunst&
bash /home/pugach/.config/polybar/launch.sh&& bspc rule -a Polybar border=off state=floating layer=below&
(sleep 2 && bspc config top_padding 21) &
pidof picom 1> /dev/null || picom --config ~/.config/picom/picom.conf &
eval "$(dbus-launch)"&
xinput --set-prop 8 'libinput Accel Speed' -1&
~/.config/conky/launch.sh

#Language
setxkbmap -option grp:caps_toggle us,ua

